# packages

# some packages you may use in our code

library(SAMEclustering)
library(xgboost)
library(uwot)
library(igraph)
library(stringr)
library(Seurat)
library(kknn)
library(garnett)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(monocle)
library(SingleCellExperiment)
library(cellassign)
library(scran)
library(SingleR)
library(Biobase)
library(SC3)
library(cidr)
library(ADPclust)
library(SIMLR)
library(scmap)
