# packages

# packages you may use in our code

library(magrittr)
library(ggplot2)
library(dplyr)
library(Matrix)
library(SAMEclustering)
library(xgboost)
library(Matrix)
library(Rtsne)
library(igraph)
library(stringr)
library(Seurat)
library(kknn)
library(umap)
library(gridExtra)
library(garnett)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(monocle)
library(SingleCellExperiment)
library(cellassign)
library(scran)
library(SingleR)
library(Biobase)
library(Seurat)
library(SingleCellExperiment)
library(SC3)
library(cidr)
library(ADPclust)
library(SIMLR)
